#
# © Copyright IBM Corporation 2017.
# This is licensed under the following license.
# The Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
# U.S. Government Users Restricted Rights:  Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
version: '3.3'
services:
    ucd-server:
        container_name: ucd-server
        image: ibmcom/ucds
        ports:
            - 8443:8443
            - 7918:7918
            - 8081:8080
    jboss-image:
        build: .
        image: jboss/wildfly-server
        depends_on:
            - ucd-server

    jboss-server:
        image: jboss/wildfly-server
        container_name: jboss-server
        ports:
            - 8080:8080
            - 9990:9990
